//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controles : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""Topolino"",
            ""id"": ""89634a47-1311-43f1-b43f-045e665a3ed0"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""af4f4738-68bd-41f8-8a01-30d031574440"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8be4e362-c771-40f6-b642-4aff1bda48c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Topolino
        m_Topolino = asset.FindActionMap("Topolino", throwIfNotFound: true);
        m_Topolino_Jump = m_Topolino.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Topolino
    private readonly InputActionMap m_Topolino;
    private ITopolinoActions m_TopolinoActionsCallbackInterface;
    private readonly InputAction m_Topolino_Jump;
    public struct TopolinoActions
    {
        private @Controles m_Wrapper;
        public TopolinoActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Topolino_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Topolino; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TopolinoActions set) { return set.Get(); }
        public void SetCallbacks(ITopolinoActions instance)
        {
            if (m_Wrapper.m_TopolinoActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_TopolinoActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_TopolinoActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_TopolinoActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_TopolinoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public TopolinoActions @Topolino => new TopolinoActions(this);
    public interface ITopolinoActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
